export default {
  zh: {
    'global.confirmed': '确诊',
    'global.recovered': '治愈',
    'global.deaths': '死亡',
    'global.increment': '新增',
    'table.title.countrynum': '共{v1}个地区',
    'table.select.placeholder': '搜索国家',
    'table.select.showall': '显示全部',
    'table.header.lastupdate': '更新时间',
    'table.header.area': '地区',
    'table.header.series': '时间线',
    'table.cell.nodata': '暂无数据',
    'map.popup.latestupdate': '最近更新',
    'gt.time.now 1-H': '过去1小时',
    'gt.time.now 4-H': '过去4小时',
    'gt.time.now 1-d': '过去1天',
    'gt.time.now 7-d': '过去7天',
    'gt.time.today 1-m': '过去30天',
    'gt.time.today 3-m': '过去90天',
    'gt.time.today 12-m': '过去1年',
    'affix.backtotop': '回到顶部',
    'affix.github': '查看源代码',
    'affix.lang': 'Switch To English',
    'app.footer.datasource': '数据源',
    'affix.gotorepo': '查看代码库',
    'area.Grand Princess': '至尊公主号',
    'area.Worldwide': '全球',
    'area.Afghanistan': '阿富汗',
    'area.Aland Islands': '奥兰群岛',
    'area.Albania': '阿尔巴尼亚',
    'area.Algeria': '阿尔及利亚',
    'area.American Samoa': '美属萨摩亚',
    'area.Andorra': '安道尔',
    'area.Angola': '安哥拉',
    'area.Anguilla': '安圭拉',
    'area.Antigua and Barbuda': '安提瓜和巴布达',
    'area.Antarctica': '南极洲',
    'area.Argentina': '阿根廷',
    'area.Armenia': '亚美尼亚',
    'area.Aruba': '阿鲁巴',
    'area.Australia': '澳大利亚',
    'area.Austria': '奥地利',
    'area.Azerbaijan': '阿塞拜疆',
    'area.Bangladesh': '孟加拉',
    'area.Bahrain': '巴林',
    'area.Bahamas, The': '巴哈马',
    'area.Barbados': '巴巴多斯',
    'area.Belarus': '白俄罗斯',
    'area.Belgium': '比利时',
    'area.Belize': '伯利兹',
    'area.Benin': '贝宁',
    'area.Bermuda': '百慕大',
    'area.Bhutan': '不丹',
    'area.Bolivia': '玻利维亚',
    'area.Bosnia and Herzegovina': '波斯尼亚和黑塞哥维那',
    'area.Botswana': '博茨瓦纳',
    'area.Bouvet Island': '布维岛',
    'area.Brazil': '巴西',
    'area.Brunei': '文莱',
    'area.Bulgaria': '保加利亚',
    'area.Burkina Faso': '布基纳法索',
    'area.Burundi': '布隆迪',
    'area.Cambodia': '柬埔寨',
    'area.Cameroon': '喀麦隆',
    'area.Canada': '加拿大',
    'area.Cabo Verde': '佛得角',
    'area.Central African Republic': '中非',
    'area.Chad': '乍得',
    'area.Chile': '智利',
    'area.Christmas Islands': '圣诞岛',
    'area.Cocos (keeling) Islands': '科科斯（基林）群岛',
    'area.Colombia': '哥伦比亚',
    'area.Comoros': '科摩罗',
    'area.Congo (Kinshasa)': '刚果（金）',
    'area.Congo (Brazzaville)': '刚果',
    'area.Cook Islands': '库克群岛',
    'area.Costa Rica': '哥斯达黎加',
    'area.Cote d\'Ivoire': '科特迪瓦',
    'area.China': '中国',
    'area.Croatia': '克罗地亚',
    'area.Cuba': '古巴',
    'area.Curaçao': '库拉索',
    'area.Czechia': '捷克',
    'area.Cyprus': '塞浦路斯',
    'area.Cruise Ship': '游轮感染病例',
    'area.Denmark': '丹麦',
    'area.Dominican Republic': '多米尼加',
    'area.Djibouti': '吉布提',
    'area.Dominica': '多米尼加',
    'area.East Timor': '东帝汶',
    'area.Ecuador': '厄瓜多尔',
    'area.Egypt': '埃及',
    'area.Equatorial Guinea': '赤道几内亚',
    'area.Eritrea': '厄立特里亚',
    'area.Estonia': '爱沙尼亚',
    'area.Ethiopia': '埃塞俄比亚',
    'area.Faroe Islands': '法罗群岛',
    'area.Fiji': '斐济',
    'area.Finland': '芬兰',
    'area.France': '法国',
    'area.Franch Metropolitan': '法国大都会',
    'area.French Guiana': '法属圭亚那',
    'area.French Polynesia': '法属波利尼西亚',
    'area.Gabon': '加蓬',
    'area.Gambia, The': '冈比亚',
    'area.Germany': '德国',
    'area.Ghana': '加纳',
    'area.Gibraltar': '直布罗陀',
    'area.Greece': '希腊',
    'area.Grenada': '格林纳达',
    'area.Greenland': '格陵兰',
    'area.Guadeloupe': '瓜德罗普岛',
    'area.Guam': '关岛',
    'area.Guatemala': '危地马拉',
    'area.Guernsey': '根西岛',
    'area.Guinea-Bissau': '几内亚比绍',
    'area.Guinea': '几内亚',
    'area.Guyana': '圭亚那',
    'area.Hong Kong': '香港',
    'area.Holy See': '圣座',
    'area.Haiti': '海地',
    'area.Honduras': '洪都拉斯',
    'area.Hungary': '匈牙利',
    'area.Iceland': '冰岛',
    'area.India': '印度',
    'area.Indonesia': '印度尼西亚',
    'area.Iran': '伊朗',
    'area.Iraq': '伊拉克',
    'area.Ireland': '爱尔兰',
    'area.Isle of Man': '马恩岛',
    'area.Israel': '以色列',
    'area.Italy': '意大利',
    'area.Jamaica': '牙买加',
    'area.Japan': '日本',
    'area.Jersey': '泽西岛',
    'area.Jordan': '约旦',
    'area.Kazakhstan': '哈萨克斯坦',
    'area.Kenya': '肯尼亚',
    'area.Kiribati': '基里巴斯',
    'area.Korea, South': '韩国',
    'area.Kosovo': '科索沃',
    'area.Korea, North': '朝鲜',
    'area.Kuwait': '科威特',
    'area.Kyrgyzstan': '吉尔吉斯斯坦',
    'area.Laos': '老挝',
    'area.Latvia': '拉脱维亚',
    'area.Lebanon': '黎巴嫩',
    'area.Lesotho': '莱索托',
    'area.Liberia': '利比里亚',
    'area.Libya': '利比亚',
    'area.Liechtenstein': '列支敦士登',
    'area.Lithuania': '立陶宛',
    'area.Luxembourg': '卢森堡',
    'area.Macau': '澳门（中国）',
    'area.North Macedonia': '马其顿',
    'area.Malawi': '马拉维',
    'area.Malaysia': '马来西亚',
    'area.Madagascar': '马达加斯加',
    'area.Maldives': '马尔代夫',
    'area.Mali': '马里',
    'area.Malta': '马耳他',
    'area.Marshall Islands': '马绍尔群岛',
    'area.Martinique': '马提尼克岛',
    'area.Mauritania': '毛里塔尼亚',
    'area.Mauritius': '毛里求斯',
    'area.Mayotte': '马约特',
    'area.Mexico': '墨西哥',
    'area.Micronesia': '密克罗尼西亚',
    'area.Moldova': '摩尔多瓦',
    'area.Monaco': '摩纳哥',
    'area.Mongolia': '蒙古',
    'area.Montenegro': '黑山',
    'area.Montserrat': '蒙特塞拉特',
    'area.Morocco': '摩洛哥',
    'area.Mozambique': '莫桑比克',
    'area.Myanmar': '缅甸',
    'area.Namibia': '纳米比亚',
    'area.Nauru': '瑙鲁',
    'area.Nepal': '尼泊尔',
    'area.Netherlands': '荷兰',
    'area.New Caledonia': '新喀里多尼亚',
    'area.New Zealand': '新西兰',
    'area.Nicaragua': '尼加拉瓜',
    'area.Niger': '尼日尔',
    'area.Nigeria': '尼日利亚',
    'area.Niue': '纽埃',
    'area.Norfolk Island': '诺福克岛',
    'area.Norway': '挪威',
    'area.Oman': '阿曼',
    'area.Pakistan': '巴基斯坦',
    'area.Palau': '帕劳',
    'area.Palestine': '巴勒斯坦',
    'area.Panama': '巴拿马',
    'area.Papua New Guinea': '巴布亚新几内亚',
    'area.Paraguay': '巴拉圭',
    'area.Peru': '秘鲁',
    'area.Philippines': '菲律宾',
    'area.Pitcairn Islands': '皮特凯恩群岛',
    'area.Poland': '波兰',
    'area.Portugal': '葡萄牙',
    'area.Puerto Rico': '波多黎各',
    'area.Qatar': '卡塔尔',
    'area.Réunion': '留尼汪',
    'area.Reunion': '留尼汪岛',
    'area.Romania': '罗马尼亚',
    'area.Rwanda': '卢旺达',
    'area.Russia': '俄罗斯',
    'area.Saint Helena': '圣赫勒拿',
    'area.Saint Kitts-Nevis': '圣基茨和尼维斯',
    'area.Saint Lucia': '圣卢西亚',
    'area.Saint Vincent and the Grenadines': '圣文森特和格林纳丁斯',
    'area.El Salvador': '萨尔瓦多',
    'area.Samoa': '萨摩亚',
    'area.San Marino': '圣马力诺',
    'area.Sao Tome and Principe': '圣多美和普林西比',
    'area.Saudi Arabia': '沙特阿拉伯',
    'area.Senegal': '塞内加尔',
    'area.Seychelles': '塞舌尔',
    'area.Sierra Leone': '塞拉利昂',
    'area.Singapore': '新加坡',
    'area.Serbia': '塞尔维亚',
    'area.Slovakia': '斯洛伐克',
    'area.Slovenia': '斯洛文尼亚',
    'area.Solomon Islands': '所罗门群岛',
    'area.Somalia': '索马里',
    'area.South Africa': '南非',
    'area.Spain': '西班牙',
    'area.Sri Lanka': '斯里兰卡',
    'area.Sudan': '苏丹',
    'area.Suriname': '苏里南',
    'area.Swaziland': '斯威士兰',
    'area.Sweden': '瑞典',
    'area.Eswatini': '斯威士兰',
    'area.Switzerland': '瑞士',
    'area.Syria': '叙利亚',
    'area.Tajikistan': '塔吉克斯坦',
    'area.Tanzania': '坦桑尼亚',
    'area.Taiwan*': '台湾',
    'area.Thailand': '泰国',
    'area.Trinidad and Tobago': '特立尼达和多巴哥',
    'area.Timor-Leste': '东帝汶',
    'area.Togo': '多哥',
    'area.Tokelau': '托克劳',
    'area.Tonga': '汤加',
    'area.Tunisia': '突尼斯',
    'area.Turkey': '土耳其',
    'area.Turkmenistan': '土库曼斯坦',
    'area.Tuvalu': '图瓦卢',
    'area.Uganda': '乌干达',
    'area.Ukraine': '乌克兰',
    'area.United Arab Emirates': '阿拉伯联合酋长国',
    'area.United Kingdom': '英国',
    'area.United States': '美国',
    'area.US': '美国',
    'area.Uruguay': '乌拉圭',
    'area.Uzbekistan': '乌兹别克斯坦',
    'area.Vanuatu': '瓦努阿图',
    'area.Vatican City': '梵蒂冈',
    'area.Venezuela': '委内瑞拉',
    'area.Vietnam': '越南',
    'area.Wallis and Futuna': '瓦利斯群岛和富图纳群岛',
    'area.Western Sahara': '西撒哈拉',
    'area.Yemen': '也门',
    'area.Yugoslavia': '南斯拉夫',
    'area.Zambia': '赞比亚',
    'area.Zimbabwe': '津巴布韦',
    'area.Yinchuan': '银川',
    'area.Shizuishan': '石嘴山',
    'area.Wuzhong': '吴忠',
    'area.Guyuan': '固原',
    'area.Zhongwei': '中卫',
    'area.Wulumuqi': '乌鲁木齐',
    'area.Kelamayi': '克拉玛依',
    'area.Lasa': '拉萨',
    'area.Huhehaote': '呼和浩特',
    'area.Baotou': '包头',
    'area.Wuhai': '乌海',
    'area.Chifeng': '赤峰',
    'area.Tongliao': '通辽',
    'area.Eerduosi': '鄂尔多斯',
    'area.Hulunbeier': '呼伦贝尔',
    'area.Bayannaoer': '巴彦淖尔',
    'area.Wulanchabu': '乌兰察布',
    'area.Nanning': '南宁',
    'area.Liuzhou': '柳州',
    'area.Guilin': '桂林',
    'area.Wuzhou': '梧州',
    'area.Beihai': '北海',
    'area.Chongzuo': '崇左',
    'area.Laibin': '来宾',
    'area.Hezhou': '贺州',
    'area.Yulin': '榆林',
    'area.Baise': '百色',
    'area.Hechi': '河池',
    'area.Qinzhou': '钦州',
    'area.Fangchenggang': '防城港',
    'area.Guigang': '贵港',
    'area.Haerbin': '哈尔滨',
    'area.Daqing': '大庆',
    'area.Qiqihaer': '齐齐哈尔',
    'area.Jiamusi': '佳木斯',
    'area.Jixi': '鸡西',
    'area.Hegang': '鹤岗',
    'area.Shuangyashan': '双鸭山',
    'area.Mudanjiang': '牡丹江',
    'area.Yichun': '宜春',
    'area.Qitaihe': '七台河',
    'area.Heihe': '黑河',
    'area.Suihua': '绥化',
    'area.Changchun': '长春',
    'area.Siping': '四平',
    'area.Liaoyuan': '辽源',
    'area.Tonghua': '通化',
    'area.Baishan': '白山',
    'area.Songyuan': '松原',
    'area.Baicheng': '白城',
    'area.Shenyang': '沈阳',
    'area.Dalian': '大连',
    'area.Anshan': '鞍山',
    'area.Fushun': '抚顺',
    'area.Benxi': '本溪',
    'area.Dandong': '丹东',
    'area.Jinzhou': '锦州',
    'area.Yingkou': '营口',
    'area.Fuxin': '阜新',
    'area.Liaoyang': '辽阳',
    'area.Panjin': '盘锦',
    'area.Tieling': '铁岭',
    'area.Chaoyang': '朝阳',
    'area.Huludao': '葫芦岛',
    'area.Shijiazhuang': '石家庄',
    'area.Tangshan': '唐山',
    'area.Handan': '邯郸',
    'area.Qinghuangdao': '秦皇岛',
    'area.Baoding': '保定',
    'area.Zhangjiakou': '张家口',
    'area.Chengde': '承德',
    'area.Langfang': '廊坊',
    'area.Cangzhou': '沧州',
    'area.Hengshui': '衡水',
    'area.Xingtai': '邢台',
    'area.Jinan': '济南',
    'area.Qingdao': '青岛',
    'area.Zibo': '淄博',
    'area.Zaozhuang': '枣庄',
    'area.Dongying': '东营',
    'area.Yantai': '烟台',
    'area.Weifang': '潍坊',
    'area.Jining': '济宁',
    'area.Taian': '泰安',
    'area.Weihai': '威海',
    'area.Rizhao': '日照',
    'area.Laiwu': '莱芜',
    'area.Linyi': '临沂',
    'area.Dezhou': '德州',
    'area.Liaocheng': '聊城',
    'area.Heze': '菏泽',
    'area.Binzhou': '滨州',
    'area.Nanjing': '南京',
    'area.Zhenjiang': '镇江',
    'area.Changzhou': '常州',
    'area.Wuxi': '无锡',
    'area.Suzhou': '宿州',
    'area.Xuzhou': '徐州',
    'area.Lianyungang': '连云港',
    'area.Huaian': '淮安',
    'area.Yancheng': '盐城',
    'area.Yangzhou': '扬州',
    'area.Taizhou': '台州',
    'area.Nantong': '南通',
    'area.Suqian': '宿迁',
    'area.Hefei': '合肥',
    'area.Bengbu': '蚌埠',
    'area.Wuhu': '芜湖',
    'area.Huainan': '淮南',
    'area.Bozhou': '亳州',
    'area.Fuyang': '阜阳',
    'area.Huaibei': '淮北',
    'area.Chuzhou': '滁州',
    'area.Anqing': '安庆',
    'area.Chaohu': '巢湖',
    'area.Maanshan': '马鞍山',
    'area.Xuancheng': '宣城',
    'area.Huangshan': '黄山',
    'area.Chizhou': '池州',
    'area.Tongling': '铜陵',
    'area.Hangzhou': '杭州',
    'area.Jiaxing': '嘉兴',
    'area.Huzhou': '湖州',
    'area.Ningbo': '宁波',
    'area.Jinhua': '金华',
    'area.Wenzhou': '温州',
    'area.Lishui': '丽水',
    'area.Shaoxing': '绍兴',
    'area.Quzhou': '衢州',
    'area.Zhoushan': '舟山',
    'area.Fuzhou': '抚州',
    'area.Xiamen': '厦门',
    'area.Quanzhou': '泉州',
    'area.Sanming': '三明',
    'area.Nanping': '南平',
    'area.Zhangzhou': '漳州',
    'area.Putian': '莆田',
    'area.Ningde': '宁德',
    'area.Longyan': '龙岩',
    'area.Guangzhou': '广州',
    'area.Shenzhen': '深圳',
    'area.Shantou': '汕头',
    'area.Huizhou': '惠州',
    'area.Zhuhai': '珠海',
    'area.Jieyang': '揭阳',
    'area.Foshan': '佛山',
    'area.Heyuan': '河源',
    'area.Yangjiang': '阳江',
    'area.Maoming': '茂名',
    'area.Zhanjiang': '湛江',
    'area.Meizhou': '梅州',
    'area.Zhaoqing': '肇庆',
    'area.Shaoguan': '韶关',
    'area.Chaozhou': '潮州',
    'area.Dongguan': '东莞',
    'area.Zhongshan': '中山',
    'area.Qingyuan': '清远',
    'area.Jiangmen': '江门',
    'area.Shanwei': '汕尾',
    'area.Yunfu': '云浮',
    'area.Haikou': '海口',
    'area.Sanya': '三亚',
    'area.Kunming': '昆明',
    'area.Qujing': '曲靖',
    'area.Yuxi': '玉溪',
    'area.Baoshan': '保山',
    'area.Zhaotong': '昭通',
    'area.Lijiang': '丽江',
    'area.Puer': '普洱',
    'area.Lincang': '临沧',
    'area.Guiyang': '贵阳',
    'area.Liupanshui': '六盘水',
    'area.Zunyi': '遵义',
    'area.Anshun': '安顺',
    'area.Chengdu': '成都',
    'area.Mianyang': '绵阳',
    'area.Deyang': '德阳',
    'area.Guangyuan': '广元',
    'area.Zigong': '自贡',
    'area.Panzhihua': '攀枝花',
    'area.Leshan': '乐山',
    'area.Nanchong': '南充',
    'area.Neijiang': '内江',
    'area.Suining': '遂宁',
    'area.Guangan': '广安',
    'area.Luzhou': '泸州',
    'area.Dazhou': '达州',
    'area.Meishan': '眉山',
    'area.Yibin': '宜宾',
    'area.Yaan': '雅安',
    'area.Ziyang': '资阳',
    'area.Changsha': '长沙',
    'area.Zhuzhou': '株洲',
    'area.Xiangtan': '湘潭',
    'area.Hengyang': '衡阳',
    'area.Yueyang': '岳阳',
    'area.Chenzhou': '郴州',
    'area.Yongzhou': '永州',
    'area.Shaoyang': '邵阳',
    'area.Huaihua': '怀化',
    'area.Changde': '常德',
    'area.Yiyang': '益阳',
    'area.Zhangjiajie': '张家界',
    'area.Loudi': '娄底',
    'area.Wuhan': '武汉',
    'area.Xiangfan': '襄樊',
    'area.Yichang': '宜昌',
    'area.Huangshi': '黄石',
    'area.Ezhou': '鄂州',
    'area.Suizhou': '随州',
    'area.Jingzhou': '荆州',
    'area.Jingmen': '荆门',
    'area.Shiyan': '十堰',
    'area.Xiaogan': '孝感',
    'area.Huanggang': '黄冈',
    'area.Xianning': '咸宁',
    'area.Zhengzhou': '郑州',
    'area.Luoyang': '洛阳',
    'area.Kaifeng': '开封',
    'area.Luohe': '漯河',
    'area.Anyang': '安阳',
    'area.Xinxiang': '新乡',
    'area.Zhoukou': '周口',
    'area.Sanmenxia': '三门峡',
    'area.Jiaozuo': '焦作',
    'area.Pingdingshan': '平顶山',
    'area.Xinyang': '信阳',
    'area.Nanyang': '南阳',
    'area.Hebi': '鹤壁',
    'area.Puyang': '濮阳',
    'area.Xuchang': '许昌',
    'area.Shangqiu': '商丘',
    'area.Zhumadian': '驻马店',
    'area.Taiyuan': '太原',
    'area.DaTong': '大同',
    'area.Xinzhou': '忻州',
    'area.Yangquan': '阳泉',
    'area.Changzhi': '长治',
    'area.Jincheng': '晋城',
    'area.Shuozhou': '朔州',
    'area.Jinzhong': '晋中',
    'area.Yuncheng': '运城',
    'area.Linfen': '临汾',
    'area.Lvliang': '吕梁',
    'area.Xian': '西安',
    'area.Xianyang': '咸阳',
    'area.Tongchuan': '铜川',
    'area.Yanan': '延安',
    'area.Baoji': '宝鸡',
    'area.Weinan': '渭南',
    'area.Hanzhoung': '汉中',
    'area.Ankang': '安康',
    'area.Shangluo': '商洛',
    'area.Lanzhou': '兰州',
    'area.Tianshui': '天水',
    'area.Pingliang': '平凉',
    'area.Jiuquan': '酒泉',
    'area.Jiayuguan': '嘉峪关',
    'area.Jinchang': '金昌',
    'area.baiyiin': '白银',
    'area.Wuwei': '武威',
    'area.Zhangye': '张掖',
    'area.Qingyang': '庆阳',
    'area.Dingxi': '定西',
    'area.Longnan': '陇南',
    'area.Xining': '西宁',
    'area.Nanchang': '南昌',
    'area.Jiujiang': '九江',
    'area.Ganzhou': '赣州',
    'area.Jian': '吉安',
    'area.Yingtan': '鹰潭',
    'area.Shangrao': '上饶',
    'area.Pingxiang': '萍乡',
    'area.Jingdezhen': '景德镇',
    'area.Xinyu': '新余',
    'area.Alabama': '亚拉巴马州',
    'area.Alaska': '阿拉斯加州',
    'area.Arizona': '亚利桑那州',
    'area.Arkansas': '阿肯色州',
    'area.California': '加利福尼亚州',
    'area.Colorado': '科罗拉多州',
    'area.Connecticut': '康涅狄格州',
    'area.Delaware': '特拉华州',
    'area.Florida': '佛罗里达州',
    'area.Georgia': '佐治亚州',
    'area.Hawaii': '夏威夷州',
    'area.Idaho': '爱达华州',
    'area.Illinois': '伊利诺州',
    'area.Indiana': '印地安那州',
    'area.Iowa': '爱荷华州',
    'area.Kansas': '堪萨斯州',
    'area.Kentucky': '肯塔基州',
    'area.Louisiana': '路易斯安那州',
    'area.Maine': '缅因州',
    'area.Maryland': '马里兰州',
    'area.Massachusetts': '麻萨诸塞州',
    'area.Michigan': '密歇根州',
    'area.Minnesota': '明尼苏达州',
    'area.Mississippi': '密西西比州',
    'area.Missouri': '密苏里州',
    'area.Montana': '蒙大拿州',
    'area.Nebraska': '内布拉斯加州',
    'area.Nevada': '内华达州',
    'area.New Hampshire': '新罕布什尔州',
    'area.New Jersey': '新泽西州',
    'area.New Mexico': '新墨西哥州',
    'area.New York': '纽约州',
    'area.North Carolina': '北卡罗来纳州',
    'area.North Dakota': '北达科他州',
    'area.Ohio': '俄亥俄州',
    'area.Oklahoma': '俄克拉何马州',
    'area.Oregon': '俄勒冈州',
    'area.Pennsylvania': '宾夕法尼亚州',
    'area.Rhode Island': '罗德岛州',
    'area.South Carolina': '南卡罗来纳州',
    'area.South Dakota': '南达科他州',
    'area.Tennessee': '田纳西州',
    'area.Texas': '得克萨斯州',
    'area.Utah': '犹他州',
    'area.Vermont': '佛蒙特州',
    'area.Virgin Islands': '维尔京群岛',
    'area.Virginia': '弗吉尼亚州',
    'area.Washington': '华盛顿州',
    'area.West Virginia': '西弗吉尼亚州',
    'area.Wisconsin': '威斯康星州',
    'area.Wyoming': '怀俄明州',
    'area.Washington, D.C.': '华盛顿哥伦比亚特区',
    'area.Beijing': '北京市',
    'area.Tianjin': '天津市',
    'area.Hebei': '河北省',
    'area.Shanxi': '山西省',
    'area.Neimenggu': '内蒙古自治区',
    'area.Liaoning': '辽宁省',
    'area.Jilin': '吉林省',
    'area.Heilongjiang': '黑龙江省',
    'area.Shanghai': '上海市',
    'area.Jiangsu': '江苏省',
    'area.Zhejiang': '浙江省',
    'area.Anhui': '安徽省',
    'area.Fujian': '福建省',
    'area.Jiangxi': '江西省',
    'area.Shandong': '山东省',
    'area.Henan': '河南省',
    'area.Hubei': '湖北省',
    'area.Hunan': '湖南省',
    'area.Guangdong': '广东省',
    'area.Guangxi': '广西壮族自治区',
    'area.Hainan': '海南省',
    'area.Chongqing': '重庆市',
    'area.Sichuan': '四川省',
    'area.Guizhong': '贵州省',
    'area.Yunnan': '云南省',
    'area.Xizang': '西藏自治区',
    'area.Shaanxi': '陕西省',
    'area.Gansu': '甘肃省',
    'area.Qinghai': '青海省',
    'area.Ningxia': '宁夏回族自治区',
    'area.Xinjiang': '新疆维吾尔自治区',
  },
  en: {
    'global.confirmed': 'Confirmed',
    'global.recovered': 'Recovered',
    'global.deaths': 'Deaths',
    'global.increment': 'Increment',
    'table.title.countrynum': 'Total {v1} Areas',
    'table.select.placeholder': 'Search area',
    'table.select.showall': 'Show All',
    'table.header.lastupdate': 'LastUpdate',
    'table.header.area': 'Area',
    'table.header.series': 'Series',
    'table.cell.nodata': 'No Data',
    'map.popup.latestupdate': 'Latest Update',
    'gt.time.now 1-H': 'Past Hour',
    'gt.time.now 4-H': 'Past 4 Hours',
    'gt.time.now 1-d': 'Past Day',
    'gt.time.now 7-d': 'Past Week',
    'gt.time.today 1-m': 'Past Month',
    'gt.time.today 3-m': 'Past 3 Months',
    'gt.time.today 12-m': 'Past Year',
    'affix.backtotop': 'Back To Top',
    'affix.github': 'Go To Repository',
    'affix.lang': '切换中文',
    'app.footer.datasource': 'Data Source',
    'area.Grand Princess': 'Grand Princess',
    'area.Worldwide': 'Worldwide',
    'area.Aruba': 'Aruba',
    'area.Afghanistan': 'Afghanistan',
    'area.Angola': 'Angola',
    'area.Anguilla': 'Anguilla',
    'area.Åland Islands': 'Åland Islands',
    'area.Albania': 'Albania',
    'area.Andorra': 'Andorra',
    'area.United Arab Emirates': 'United Arab Emirates',
    'area.Argentina': 'Argentina',
    'area.Armenia': 'Armenia',
    'area.American Samoa': 'American Samoa',
    'area.Antarctica': 'Antarctica',
    'area.French Southern and Antarctic Lands': 'French Southern and Antarctic Lands',
    'area.Antigua and Barbuda': 'Antigua and Barbuda',
    'area.Australia': 'Australia',
    'area.Austria': 'Austria',
    'area.Azerbaijan': 'Azerbaijan',
    'area.Burundi': 'Burundi',
    'area.Belgium': 'Belgium',
    'area.Benin': 'Benin',
    'area.Burkina Faso': 'Burkina Faso',
    'area.Bangladesh': 'Bangladesh',
    'area.Bulgaria': 'Bulgaria',
    'area.Bahrain': 'Bahrain',
    'area.Bahamas, The': 'Bahamas',
    'area.Bosnia and Herzegovina': 'Bosnia and Herzegovina',
    'area.Saint Barthélemy': 'Saint Barthélemy',
    'area.Saint Helena, Ascension and Tristan da Cunha': 'Saint Helena, Ascension and Tristan da Cunha',
    'area.Belarus': 'Belarus',
    'area.Belize': 'Belize',
    'area.Bermuda': 'Bermuda',
    'area.Bolivia': 'Bolivia',
    'area.Caribbean Netherlands': 'Caribbean Netherlands',
    'area.Brazil': 'Brazil',
    'area.Barbados': 'Barbados',
    'area.Brunei': 'Brunei',
    'area.Bhutan': 'Bhutan',
    'area.Bouvet Island': 'Bouvet Island',
    'area.Botswana': 'Botswana',
    'area.Central African Republic': 'Central African Republic',
    'area.Canada': 'Canada',
    'area.Cocos (Keeling) Islands': 'Cocos (Keeling) Islands',
    'area.Cote d\'Ivoire': 'Cote d\'Ivoire',
    'area.Switzerland': 'Switzerland',
    'area.Chile': 'Chile',
    'area.China': 'China',
    'area.Ivory Coast': 'Ivory Coast',
    'area.Cameroon': 'Cameroon',
    'area.Congo (Kinshasa)': 'Congo (Kinshasa)',
    'area.Congo (Brazzaville)': 'Congo (Brazzaville)',
    'area.Cook Islands': 'Cook Islands',
    'area.Colombia': 'Colombia',
    'area.Comoros': 'Comoros',
    'area.Cabo Verde': 'Cabo Verde',
    'area.Costa Rica': 'Costa Rica',
    'area.Cuba': 'Cuba',
    'area.Curaçao': 'Curaçao',
    'area.Christmas Island': 'Christmas Island',
    'area.Cayman Islands': 'Cayman Islands',
    'area.Cyprus': 'Cyprus',
    'area.Cruise Ship': 'Cruise Ship',
    'area.Czechia': 'Czechia',
    'area.Germany': 'Germany',
    'area.Djibouti': 'Djibouti',
    'area.Dominica': 'Dominica',
    'area.Denmark': 'Denmark',
    'area.Dominican Republic': 'Dominican Republic',
    'area.Algeria': 'Algeria',
    'area.Ecuador': 'Ecuador',
    'area.Egypt': 'Egypt',
    'area.Eritrea': 'Eritrea',
    'area.Western Sahara': 'Western Sahara',
    'area.Spain': 'Spain',
    'area.Estonia': 'Estonia',
    'area.Ethiopia': 'Ethiopia',
    'area.Finland': 'Finland',
    'area.Fiji': 'Fiji',
    'area.Falkland Islands': 'Falkland Islands',
    'area.France': 'France',
    'area.Faroe Islands': 'Faroe Islands',
    'area.Micronesia': 'Micronesia',
    'area.Gabon': 'Gabon',
    'area.United Kingdom': 'United Kingdom',
    'area.Guernsey': 'Guernsey',
    'area.Ghana': 'Ghana',
    'area.Gibraltar': 'Gibraltar',
    'area.Guinea': 'Guinea',
    'area.Guadeloupe': 'Guadeloupe',
    'area.Gambia, The': 'Gambia',
    'area.Guinea-Bissau': 'Guinea-Bissau',
    'area.Equatorial Guinea': 'Equatorial Guinea',
    'area.Greece': 'Greece',
    'area.Grenada': 'Grenada',
    'area.Greenland': 'Greenland',
    'area.Guatemala': 'Guatemala',
    'area.French Guiana': 'French Guiana',
    'area.Guyana': 'Guyana',
    'area.Holy See': 'Holy See',
    'area.Hong Kong': 'Hong Kong',
    'area.Heard Island and McDonald Islands': 'Heard Island and McDonald Islands',
    'area.Honduras': 'Honduras',
    'area.Croatia': 'Croatia',
    'area.Haiti': 'Haiti',
    'area.Hungary': 'Hungary',
    'area.Indonesia': 'Indonesia',
    'area.Isle of Man': 'Isle of Man',
    'area.India': 'India',
    'area.British Indian Ocean Territory': 'British Indian Ocean Territory',
    'area.Ireland': 'Ireland',
    'area.Iran': 'Iran',
    'area.Iraq': 'Iraq',
    'area.Iceland': 'Iceland',
    'area.Israel': 'Israel',
    'area.Italy': 'Italy',
    'area.Jamaica': 'Jamaica',
    'area.Jersey': 'Jersey',
    'area.Jordan': 'Jordan',
    'area.Japan': 'Japan',
    'area.Kazakhstan': 'Kazakhstan',
    'area.Kenya': 'Kenya',
    'area.Kyrgyzstan': 'Kyrgyzstan',
    'area.Cambodia': 'Cambodia',
    'area.Kiribati': 'Kiribati',
    'area.Saint Kitts and Nevis': 'Saint Kitts and Nevis',
    'area.Korea, South': 'Korea, South',
    'area.Kosovo': 'Kosovo',
    'area.Kuwait': 'Kuwait',
    'area.Laos': 'Laos',
    'area.Lebanon': 'Lebanon',
    'area.Liberia': 'Liberia',
    'area.Libya': 'Libya',
    'area.Saint Lucia': 'Saint Lucia',
    'area.Liechtenstein': 'Liechtenstein',
    'area.Sri Lanka': 'Sri Lanka',
    'area.Lesotho': 'Lesotho',
    'area.Lithuania': 'Lithuania',
    'area.Luxembourg': 'Luxembourg',
    'area.Latvia': 'Latvia',
    'area.Macau': 'Macau',
    'area.Saint Martin': 'Saint Martin',
    'area.Morocco': 'Morocco',
    'area.Monaco': 'Monaco',
    'area.Moldova': 'Moldova',
    'area.Madagascar': 'Madagascar',
    'area.Maldives': 'Maldives',
    'area.Mexico': 'Mexico',
    'area.Marshall Islands': 'Marshall Islands',
    'area.North Macedonia': 'North Macedonia',
    'area.Mali': 'Mali',
    'area.Malta': 'Malta',
    'area.Myanmar': 'Myanmar',
    'area.Montenegro': 'Montenegro',
    'area.Mongolia': 'Mongolia',
    'area.Northern Mariana Islands': 'Northern Mariana Islands',
    'area.Mozambique': 'Mozambique',
    'area.Mauritania': 'Mauritania',
    'area.Montserrat': 'Montserrat',
    'area.Martinique': 'Martinique',
    'area.Mauritius': 'Mauritius',
    'area.Malawi': 'Malawi',
    'area.Malaysia': 'Malaysia',
    'area.Mayotte': 'Mayotte',
    'area.Namibia': 'Namibia',
    'area.New Caledonia': 'New Caledonia',
    'area.Niger': 'Niger',
    'area.Norfolk Island': 'Norfolk Island',
    'area.Nigeria': 'Nigeria',
    'area.Nicaragua': 'Nicaragua',
    'area.Niue': 'Niue',
    'area.Netherlands': 'Netherlands',
    'area.Norway': 'Norway',
    'area.Nepal': 'Nepal',
    'area.Nauru': 'Nauru',
    'area.New Zealand': 'New Zealand',
    'area.Oman': 'Oman',
    'area.Pakistan': 'Pakistan',
    'area.Palau': 'Palau',
    'area.Panama': 'Panama',
    'area.Pitcairn Islands': 'Pitcairn Islands',
    'area.Peru': 'Peru',
    'area.Philippines': 'Philippines',
    'area.Papua New Guinea': 'Papua New Guinea',
    'area.Poland': 'Poland',
    'area.Korea, North': 'Korea, North',
    'area.Portugal': 'Portugal',
    'area.Paraguay': 'Paraguay',
    'area.Palestine': 'Palestine',
    'area.French Polynesia': 'French Polynesia',
    'area.Qatar': 'Qatar',
    'area.Réunion': 'Réunion',
    'area.Romania': 'Romania',
    'area.Russia': 'Russia',
    'area.Rwanda': 'Rwanda',
    'area.Saudi Arabia': 'Saudi Arabia',
    'area.Sudan': 'Sudan',
    'area.Senegal': 'Senegal',
    'area.Singapore': 'Singapore',
    'area.South Georgia': 'South Georgia',
    'area.Svalbard and Jan Mayen': 'Svalbard and Jan Mayen',
    'area.Solomon Islands': 'Solomon Islands',
    'area.Sierra Leone': 'Sierra Leone',
    'area.El Salvador': 'El Salvador',
    'area.San Marino': 'San Marino',
    'area.Somalia': 'Somalia',
    'area.Saint Pierre and Miquelon': 'Saint Pierre and Miquelon',
    'area.Serbia': 'Serbia',
    'area.South Sudan': 'South Sudan',
    'area.São Tomé and Príncipe': 'São Tomé and Príncipe',
    'area.Suriname': 'Suriname',
    'area.Slovakia': 'Slovakia',
    'area.Slovenia': 'Slovenia',
    'area.Sweden': 'Sweden',
    'area.Eswatini': 'Eswatini',
    'area.Sint Maarten': 'Sint Maarten',
    'area.Seychelles': 'Seychelles',
    'area.Syria': 'Syria',
    'area.Turks and Caicos Islands': 'Turks and Caicos Islands',
    'area.Chad': 'Chad',
    'area.Togo': 'Togo',
    'area.Thailand': 'Thailand',
    'area.Tajikistan': 'Tajikistan',
    'area.Tokelau': 'Tokelau',
    'area.Turkmenistan': 'Turkmenistan',
    'area.Timor-Leste': 'Timor-Leste',
    'area.Tonga': 'Tonga',
    'area.Trinidad and Tobago': 'Trinidad and Tobago',
    'area.Tunisia': 'Tunisia',
    'area.Turkey': 'Turkey',
    'area.Tuvalu': 'Tuvalu',
    'area.Taiwan*': 'Taiwan',
    'area.Tanzania': 'Tanzania',
    'area.Uganda': 'Uganda',
    'area.Ukraine': 'Ukraine',
    'area.United States Minor Outlying Islands': 'United States Minor Outlying Islands',
    'area.Uruguay': 'Uruguay',
    'area.United States': 'United States',
    'area.US': 'United States',
    'area.Uzbekistan': 'Uzbekistan',
    'area.Vatican City': 'Vatican City',
    'area.Saint Vincent and the Grenadines': 'Saint Vincent and the Grenadines',
    'area.Venezuela': 'Venezuela',
    'area.British Virgin Islands': 'British Virgin Islands',
    'area.United States Virgin Islands': 'United States Virgin Islands',
    'area.Vietnam': 'Vietnam',
    'area.Vanuatu': 'Vanuatu',
    'area.Wallis and Futuna': 'Wallis and Futuna',
    'area.Samoa': 'Samoa',
    'area.Yemen': 'Yemen',
    'area.South Africa': 'South Africa',
    'area.Zambia': 'Zambia',
    'area.Zimbabwe': 'Zimbabwe',
    'area.Beijing': 'Beijing',
    'area.Tianjin': 'Tianjin',
    'area.Shanghai': 'Shanghai',
    'area.Yinchuan': 'Yinchuan',
    'area.Shizuishan': 'Shizuishan',
    'area.Wuzhong': 'Wuzhong',
    'area.Guyuan': 'Guyuan',
    'area.Zhongwei': 'Zhongwei',
    'area.Wulumuqi': 'Wulumuqi',
    'area.Kelamayi': 'Kelamayi',
    'area.Lasa': 'Lasa',
    'area.Huhehaote': 'Huhehaote',
    'area.Baotou': 'Baotou',
    'area.Wuhai': 'Wuhai',
    'area.Chifeng': 'Chifeng',
    'area.Tongliao': 'Tongliao',
    'area.Eerduosi': 'Eerduosi',
    'area.Hulunbeier': 'Hulunbeier',
    'area.Bayannaoer': 'Bayannaoer',
    'area.Wulanchabu': 'Wulanchabu',
    'area.Nanning': 'Nanning',
    'area.Liuzhou': 'Liuzhou',
    'area.Guilin': 'Guilin',
    'area.Wuzhou': 'Wuzhou',
    'area.Beihai': 'Beihai',
    'area.Chongzuo': 'Chongzuo',
    'area.Laibin': 'Laibin',
    'area.Hezhou': 'Hezhou',
    'area.Yulin': 'Yulin',
    'area.Baise': 'Baise',
    'area.Hechi': 'Hechi',
    'area.Qinzhou': 'Qinzhou',
    'area.Fangchenggang': 'Fangchenggang',
    'area.Guigang': 'Guigang',
    'area.Haerbin': 'Haerbin',
    'area.Daqing': 'Daqing',
    'area.Qiqihaer': 'Qiqihaer',
    'area.Jiamusi': 'Jiamusi',
    'area.Jixi': 'Jixi',
    'area.Hegang': 'Hegang',
    'area.Shuangyashan': 'Shuangyashan',
    'area.Mudanjiang': 'Mudanjiang',
    'area.Yichun': 'Yichun',
    'area.Qitaihe': 'Qitaihe',
    'area.Heihe': 'Heihe',
    'area.Suihua': 'Suihua',
    'area.Changchun': 'Changchun',
    'area.Siping': 'Siping',
    'area.Liaoyuan': 'Liaoyuan',
    'area.Tonghua': 'Tonghua',
    'area.Baishan': 'Baishan',
    'area.Songyuan': 'Songyuan',
    'area.Baicheng': 'Baicheng',
    'area.Shenyang': 'Shenyang',
    'area.Dalian': 'Dalian',
    'area.Anshan': 'Anshan',
    'area.Fushun': 'Fushun',
    'area.Benxi': 'Benxi',
    'area.Dandong': 'Dandong',
    'area.Jinzhou': 'Jinzhou',
    'area.Yingkou': 'Yingkou',
    'area.Fuxin': 'Fuxin',
    'area.Liaoyang': 'Liaoyang',
    'area.Panjin': 'Panjin',
    'area.Tieling': 'Tieling',
    'area.Chaoyang': 'Chaoyang',
    'area.Huludao': 'Huludao',
    'area.Shijiazhuang': 'Shijiazhuang',
    'area.Tangshan': 'Tangshan',
    'area.Handan': 'Handan',
    'area.Qinghuangdao': 'Qinghuangdao',
    'area.Baoding': 'Baoding',
    'area.Zhangjiakou': 'Zhangjiakou',
    'area.Chengde': 'Chengde',
    'area.Langfang': 'Langfang',
    'area.Cangzhou': 'Cangzhou',
    'area.Hengshui': 'Hengshui',
    'area.Xingtai': 'Xingtai',
    'area.Jinan': 'Jinan',
    'area.Qingdao': 'Qingdao',
    'area.Zibo': 'Zibo',
    'area.Zaozhuang': 'Zaozhuang',
    'area.Dongying': 'Dongying',
    'area.Yantai': 'Yantai',
    'area.Weifang': 'Weifang',
    'area.Jining': 'Jining',
    'area.Taian': 'Taian',
    'area.Weihai': 'Weihai',
    'area.Rizhao': 'Rizhao',
    'area.Laiwu': 'Laiwu',
    'area.Linyi': 'Linyi',
    'area.Dezhou': 'Dezhou',
    'area.Liaocheng': 'Liaocheng',
    'area.Heze': 'Heze',
    'area.Binzhou': 'Binzhou',
    'area.Nanjing': 'Nanjing',
    'area.Zhenjiang': 'Zhenjiang',
    'area.Changzhou': 'Changzhou',
    'area.Wuxi': 'Wuxi',
    'area.Suzhou': 'Suzhou',
    'area.Xuzhou': 'Xuzhou',
    'area.Lianyungang': 'Lianyungang',
    'area.Huaian': 'Huaian',
    'area.Yancheng': 'Yancheng',
    'area.Yangzhou': 'Yangzhou',
    'area.Taizhou': 'Taizhou',
    'area.Nantong': 'Nantong',
    'area.Suqian': 'Suqian',
    'area.Hefei': 'Hefei',
    'area.Bengbu': 'Bengbu',
    'area.Wuhu': 'Wuhu',
    'area.Huainan': 'Huainan',
    'area.Bozhou': 'Bozhou',
    'area.Fuyang': 'Fuyang',
    'area.Huaibei': 'Huaibei',
    'area.Chuzhou': 'Chuzhou',
    'area.Anqing': 'Anqing',
    'area.Chaohu': 'Chaohu',
    'area.Maanshan': 'Maanshan',
    'area.Xuancheng': 'Xuancheng',
    'area.Huangshan': 'Huangshan',
    'area.Chizhou': 'Chizhou',
    'area.Tongling': 'Tongling',
    'area.Hangzhou': 'Hangzhou',
    'area.Jiaxing': 'Jiaxing',
    'area.Huzhou': 'Huzhou',
    'area.Ningbo': 'Ningbo',
    'area.Jinhua': 'Jinhua',
    'area.Wenzhou': 'Wenzhou',
    'area.Lishui': 'Lishui',
    'area.Shaoxing': 'Shaoxing',
    'area.Quzhou': 'Quzhou',
    'area.Zhoushan': 'Zhoushan',
    'area.Fuzhou': 'Fuzhou',
    'area.Xiamen': 'Xiamen',
    'area.Quanzhou': 'Quanzhou',
    'area.Sanming': 'Sanming',
    'area.Nanping': 'Nanping',
    'area.Zhangzhou': 'Zhangzhou',
    'area.Putian': 'Putian',
    'area.Ningde': 'Ningde',
    'area.Longyan': 'Longyan',
    'area.Guangzhou': 'Guangzhou',
    'area.Shenzhen': 'Shenzhen',
    'area.Shantou': 'Shantou',
    'area.Huizhou': 'Huizhou',
    'area.Zhuhai': 'Zhuhai',
    'area.Jieyang': 'Jieyang',
    'area.Foshan': 'Foshan',
    'area.Heyuan': 'Heyuan',
    'area.Yangjiang': 'Yangjiang',
    'area.Maoming': 'Maoming',
    'area.Zhanjiang': 'Zhanjiang',
    'area.Meizhou': 'Meizhou',
    'area.Zhaoqing': 'Zhaoqing',
    'area.Shaoguan': 'Shaoguan',
    'area.Chaozhou': 'Chaozhou',
    'area.Dongguan': 'Dongguan',
    'area.Zhongshan': 'Zhongshan',
    'area.Qingyuan': 'Qingyuan',
    'area.Jiangmen': 'Jiangmen',
    'area.Shanwei': 'Shanwei',
    'area.Yunfu': 'Yunfu',
    'area.Haikou': 'Haikou',
    'area.Sanya': 'Sanya',
    'area.Kunming': 'Kunming',
    'area.Qujing': 'Qujing',
    'area.Yuxi': 'Yuxi',
    'area.Baoshan': 'Baoshan',
    'area.Zhaotong': 'Zhaotong',
    'area.Lijiang': 'Lijiang',
    'area.Puer': 'Puer',
    'area.Lincang': 'Lincang',
    'area.Guiyang': 'Guiyang',
    'area.Liupanshui': 'Liupanshui',
    'area.Zunyi': 'Zunyi',
    'area.Anshun': 'Anshun',
    'area.Chengdu': 'Chengdu',
    'area.Mianyang': 'Mianyang',
    'area.Deyang': 'Deyang',
    'area.Guangyuan': 'Guangyuan',
    'area.Zigong': 'Zigong',
    'area.Panzhihua': 'Panzhihua',
    'area.Leshan': 'Leshan',
    'area.Nanchong': 'Nanchong',
    'area.Neijiang': 'Neijiang',
    'area.Suining': 'Suining',
    'area.Guangan': 'Guangan',
    'area.Luzhou': 'Luzhou',
    'area.Dazhou': 'Dazhou',
    'area.Meishan': 'Meishan',
    'area.Yibin': 'Yibin',
    'area.Yaan': 'Yaan',
    'area.Ziyang': 'Ziyang',
    'area.Changsha': 'Changsha',
    'area.Zhuzhou': 'Zhuzhou',
    'area.Xiangtan': 'Xiangtan',
    'area.Hengyang': 'Hengyang',
    'area.Yueyang': 'Yueyang',
    'area.Chenzhou': 'Chenzhou',
    'area.Yongzhou': 'Yongzhou',
    'area.Shaoyang': 'Shaoyang',
    'area.Huaihua': 'Huaihua',
    'area.Changde': 'Changde',
    'area.Yiyang': 'Yiyang',
    'area.Zhangjiajie': 'Zhangjiajie',
    'area.Loudi': 'Loudi',
    'area.Wuhan': 'Wuhan',
    'area.Xiangfan': 'Xiangfan',
    'area.Yichang': 'Yichang',
    'area.Huangshi': 'Huangshi',
    'area.Ezhou': 'Ezhou',
    'area.Suizhou': 'Suizhou',
    'area.Jingzhou': 'Jingzhou',
    'area.Jingmen': 'Jingmen',
    'area.Shiyan': 'Shiyan',
    'area.Xiaogan': 'Xiaogan',
    'area.Huanggang': 'Huanggang',
    'area.Xianning': 'Xianning',
    'area.Zhengzhou': 'Zhengzhou',
    'area.Luoyang': 'Luoyang',
    'area.Kaifeng': 'Kaifeng',
    'area.Luohe': 'Luohe',
    'area.Anyang': 'Anyang',
    'area.Xinxiang': 'Xinxiang',
    'area.Zhoukou': 'Zhoukou',
    'area.Sanmenxia': 'Sanmenxia',
    'area.Jiaozuo': 'Jiaozuo',
    'area.Pingdingshan': 'Pingdingshan',
    'area.Xinyang': 'Xinyang',
    'area.Nanyang': 'Nanyang',
    'area.Hebi': 'Hebi',
    'area.Puyang': 'Puyang',
    'area.Xuchang': 'Xuchang',
    'area.Shangqiu': 'Shangqiu',
    'area.Zhumadian': 'Zhumadian',
    'area.Taiyuan': 'Taiyuan',
    'area.DaTong': 'DaTong',
    'area.Xinzhou': 'Xinzhou',
    'area.Yangquan': 'Yangquan',
    'area.Changzhi': 'Changzhi',
    'area.Jincheng': 'Jincheng',
    'area.Shuozhou': 'Shuozhou',
    'area.Jinzhong': 'Jinzhong',
    'area.Yuncheng': 'Yuncheng',
    'area.Linfen': 'Linfen',
    'area.Lvliang': 'Lvliang',
    'area.Xian': 'Xian',
    'area.Xianyang': 'Xianyang',
    'area.Tongchuan': 'Tongchuan',
    'area.Yanan': 'Yanan',
    'area.Baoji': 'Baoji',
    'area.Weinan': 'Weinan',
    'area.Hanzhoung': 'Hanzhoung',
    'area.Ankang': 'Ankang',
    'area.Shangluo': 'Shangluo',
    'area.Lanzhou': 'Lanzhou',
    'area.Tianshui': 'Tianshui',
    'area.Pingliang': 'Pingliang',
    'area.Jiuquan': 'Jiuquan',
    'area.Jiayuguan': 'Jiayuguan',
    'area.Jinchang': 'Jinchang',
    'area.baiyiin': 'baiyiin',
    'area.Wuwei': 'Wuwei',
    'area.Zhangye': 'Zhangye',
    'area.Qingyang': 'Qingyang',
    'area.Dingxi': 'Dingxi',
    'area.Longnan': 'Longnan',
    'area.Xining': 'Xining',
    'area.Nanchang': 'Nanchang',
    'area.Jiujiang': 'Jiujiang',
    'area.Ganzhou': 'Ganzhou',
    'area.Jian': 'Jian',
    'area.Yingtan': 'Yingtan',
    'area.Shangrao': 'Shangrao',
    'area.Pingxiang': 'Pingxiang',
    'area.Jingdezhen': 'Jingdezhen',
    'area.Xinyu': 'Xinyu',
    'area.Alabama': 'Alabama',
    'area.Alaska': 'Alaska',
    'area.Arizona': 'Arizona',
    'area.Arkansas': 'Arkansas',
    'area.California': 'California',
    'area.Colorado': 'Colorado',
    'area.Connecticut': 'Connecticut',
    'area.Delaware': 'Delaware',
    'area.Florida': 'Florida',
    'area.Georgia': 'Georgia',
    'area.Guam': 'Guam',
    'area.Hawaii': 'Hawaii',
    'area.Idaho': 'Idaho',
    'area.Illinois': 'Illinois',
    'area.Indiana': 'Indiana',
    'area.Iowa': 'Iowa',
    'area.Kansas': 'Kansas',
    'area.Kentucky': 'Kentucky',
    'area.Louisiana': 'Louisiana',
    'area.Maine': 'Maine',
    'area.Maryland': 'Maryland',
    'area.Massachusetts': 'Massachusetts',
    'area.Michigan': 'Michigan',
    'area.Minnesota': 'Minnesota',
    'area.Mississippi': 'Mississippi',
    'area.Missouri': 'Missouri',
    'area.Montana': 'Montana',
    'area.Nebraska': 'Nebraska',
    'area.Nevada': 'Nevada',
    'area.New Hampshire': 'New Hampshire',
    'area.New Jersey': 'New Jersey',
    'area.New Mexico': 'New Mexico',
    'area.New York': 'New York',
    'area.North Carolina': 'North Carolina',
    'area.North Dakota': 'North Dakota',
    'area.Ohio': 'Ohio',
    'area.Oklahoma': 'Oklahoma',
    'area.Oregon': 'Oregon',
    'area.Pennsylvania': 'Pennsylvania',
    'area.Puerto Rico': 'Puerto Rico',
    'area.Rhode Island': 'Rhode Island',
    'area.South Carolina': 'South Carolina',
    'area.South Dakota': 'South Dakota',
    'area.Tennessee': 'Tennessee',
    'area.Texas': 'Texas',
    'area.Utah': 'Utah',
    'area.Vermont': 'Vermont',
    'area.Virgin Islands': 'Virgin Islands',
    'area.Virginia': 'Virginia',
    'area.Washington': 'Washington',
    'area.West Virginia': 'West Virginia',
    'area.Wisconsin': 'Wisconsin',
    'area.Wyoming': 'Wyoming',
    'area.Washington, D.C.': 'Washington, D.C.',
    'area.Hebei': 'Hebei',
    'area.Shanxi': 'Shanxi',
    'area.Neimenggu': 'Neimenggu',
    'area.Liaoning': 'Liaoning',
    'area.Jilin': 'Jilin',
    'area.Heilongjiang': 'Heilongjiang',
    'area.Jiangsu': 'Jiangsu',
    'area.Zhejiang': 'Zhejiang',
    'area.Anhui': 'Anhui',
    'area.Fujian': 'Fujian',
    'area.Jiangxi': 'Jiangxi',
    'area.Shandong': 'Shandong',
    'area.Henan': 'Henan',
    'area.Hubei': 'Hubei',
    'area.Hunan': 'Hunan',
    'area.Guangdong': 'Guangdong',
    'area.Guangxi': 'Guangxi',
    'area.Hainan': 'Hainan',
    'area.Chongqing': 'Chongqing',
    'area.Sichuan': 'Sichuan',
    'area.Guizhong': 'Guizhong',
    'area.Yunnan': 'Yunnan',
    'area.Xizang': 'Xizang',
    'area.Shaanxi': 'Shaanxi',
    'area.Gansu': 'Gansu',
    'area.Qinghai': 'Qinghai',
    'area.Ningxia': 'Ningxia',
    'area.Xinjiang': 'Xinjiang',
  },
};